# Generated by Django 2.2.1 on 2019-05-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_corrida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dateInicioInscricao', models.DateField()),
                ('dateFimInscricao', models.DateField()),
                ('etapa', models.ManyToManyField(to='inscricao.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnh', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('emerg', models.CharField(max_length=100)),
                ('pl_saude', models.CharField(max_length=100)),
                ('al_db', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tp_Sangue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navegador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navegador', to='inscricao.Pessoa')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto', to='inscricao.Pessoa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.Veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colocao', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Evento')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Time')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='pista',
            field=models.ForeignKey(on_delete=False, to='inscricao.Pista'),
        ),
    ]
