# Generated by Django 2.2.1 on 2019-05-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo_sang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Tp_Sangue'),
        ),
    ]
