# Generated by Django 2.2.1 on 2019-05-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_pessoa_tipo_sang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_sang',
            field=models.ForeignKey(default='tipo_s', on_delete=django.db.models.deletion.PROTECT, to='inscricao.Tp_Sangue'),
        ),
    ]
