# Generated by Django 2.2.1 on 2019-05-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_auto_20190507_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_sang',
            field=models.ForeignKey(default='tipo_sang', on_delete=django.db.models.deletion.PROTECT, to='inscricao.Tp_Sangue'),
        ),
    ]
