# Generated by Django 2.2.1 on 2019-05-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_auto_20190529_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
